### ISSUE TITLE
閉じていないパスを描画する

### ISSUE THREAD

**Issue by Kiikurage** [Kiikurage/drawing2#44]
- 機能の説明
    - 現在は閉じているパスしか表示されない
    - 閉じていないパスも表示する

- 動機・解決したい問題
    - 矢印や折れ線などの線を描画したいので。

- dev steps
  - Graphクラスでは、閉じた領域の判定のために、閉じていないパスを削除するnormalize処理をしている
  - これはそのままにして、Edgeのレンダリングには、normalize前の元のグラフをそのまま使用するよう変更する。
  -  塗りつぶし領域とは別に、normalize前のEdgeをレンダリングするための`<path>`タグをPathViewに追加する

**Comment by not-elm** [comment]
![タイトルなし](https://github.com/user-attachments/assets/01ee0e81-4b2f-4e95-b8d2-4b7f0f292ac7)

**Comment by Kiikurage** [comment]
砂時計型の三角形の領域を塗りつぶしで表示し、Edgeは全てそのまま表示する感じです
